# Site settings
title: 极客浩浩
SEOTitle: 陈浩鑫的博客 | jikehaohao Blog
header-img: img/home-bg.jpg
email: chenhaoxin@finupgroup.com
description: "当你的才华撑不起你的野心时，只有静下心来好好学习！"
keyword: "陈浩鑫,Chen浩鑫,海贼迷，动漫爱好者，王者荣耀，吃鸡大神，互联网,python,运维,开发工程师,设计,努力&不服输&爱拼&极客"
url: "https://jikehaohao.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     chenhaoxinrepo
zhihu_username:     chenhaoxinrepo
github_username:    jikehaohao
twitter_username:   jikehaohao
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: jikehaohao

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: jikehaohao.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends-url: [
    {
        title: "鸟哥Linux私房菜篇",
        href: "http://linux.vbird.org/"
    },{
        title: "菜鸟奔袭",
        href: "http://www.runoob.com/"
    },{
        title: "博客园创想天地",
        href: "https://i.cnblogs.com/posts/"
    },{
        title: "前端组件大全",
        href: "https://v3.bootcss.com/components/"
    },{
        title: "前端在线",
        href: "https://runjs.cn/code"
    }
]

